### ISSUE TITLE
Decrease Wobble option stops new 10 gauge shotgun from shooting.

### ISSUE THREAD

**Issue by Mom-Kat** [rollerb/cotw-mod-builder#4]
Using the 'Decrease Wobble'  settings makes the new shotgun not shoot, but if you instead modify the steady hands skill, it works.

**Comment by aphoenixx** [comment]
I'm not so sure its decrease wobble (although that may also bug it out), after reloading with a bunch of options selected or left out it looks like any changes to the Increase Speed option break the guns for me. Even adding it to the mod list but keeping the values at default.

**Comment by cpypasta** [comment]
i will just keep one of these issues open since many are related
