### ISSUE TITLE
New guns won't reload. Glitch during animation.

### ISSUE THREAD

**Issue by weaponfx** [rollerb/cotw-mod-builder#6]
Hey B,

Great work as usual, this mod is it's own bit of software and a quality example of coding.
Regarding the guns, I have an issue where none will reload, the animation starts to drop the gun down to reload however it glitchs back to the normal in hand position without completing the animation/reload.
They do fire without an issue except for the shotgun, I cannot aim and fire, only hip fire and even then it doesn't always work. Attached is the Mod Builder save file I'm using in game, I hope it helps. Happy to provide more info with your direction @cpypasta 
[v2.json](https://github.com/cpypasta/cotw-mod-builder/files/14587165/v2.json)

**Comment by cpypasta** [comment]
just keeping one of these issues open, since they are all related
