### ISSUE TITLE
Unhandled exception when building mods

### ISSUE THREAD

**Issue by Roope00** [rollerb/cotw-mod-builder#8]
First of all, thanks a lot for the mod and still updating it!

With the newest game and modbuilder updates, the modbuilder fails to build with the selected mods for me. The error it gives is as follows: 

```
Unhandled exception in script
Failed to execute script 'modbuilder' due to unhandled exception: 'NoneType' object has no attribute 'get_files'

Traceback (most recent call last):
  File "modbuilder.py", line 4, in
  File "modbuilder\__main__.py", line 4, in main
  File "modbuilder\gui.py", line 268, in main
AttributeError: 'NoneType' object has no attribute 'get_files'
```

It however seems to work with the default presets. I'll attach the mod preset I've used which gives the error.
[Roopes preset.json](https://github.com/cpypasta/cotw-mod-builder/files/14590836/Roopes.preset.json)

**Comment by cpypasta** [comment]
Thanks for sharing your save file. The newest release will now avoid this error.
